#!/bin/bash

script_dir=$(dirname "$0")
cd "$script_dir/bin"
build_version=$(git describe --always --abbrev=7 --dirty)
for f in *; do
    bin_version=$("./$f" version | awk '{ print $3 }' | sed -r -e 's/,$//')
    aws s3 cp "$f" "s3://aeris-deployment/ec2/bin/sensu/$build_version/$b"
done
