#!/bin/bash

script_dir=$(dirname "$0")
cd "$script_dir"

build_version=$(git describe --always --abbrev=7 --dirty)
read -r -d '' ldflags <<EOF
    -X "github.com/sensu/sensu-go/version.BuildDate=$(date --iso-8601=minute)"
    -X "github.com/sensu/sensu-go/version.BuildSHA=$(git rev-parse HEAD)"
    -X "github.com/sensu/sensu-go/version.Version=$build_version"
EOF
build_extra_args=(-ldflags "$ldflags")
binaries=(sensu-agent sensu-backend sensuctl)
for b in "${binaries[@]}"; do
    go build "${build_extra_args[@]}" -o "bin/$b" "./cmd/$b"
done
